version: '3'

services:
    #Baraka App
    app:
        build:
            context: ""
            dockerfile: ./Dockerfile
        image: baraka
        container_name: baraka-app
        restart: on-failure
        tty: true
        environment:
            APP_DEBUG: "true"
            DB_HOST: db
            DB_USERNAME: root
            DB_PASSWORD: baraka
            DB_DATABASE: baraka
        ports:
          - 8000:80
        depends_on:
            - db
        volumes:
            - ./:/var/www/html
            - ./local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:5.7
        container_name: baraka-db
        restart: on-failure
        tty: true
        ports:
            - "3307:3306"
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: baraka
            MYSQL_ROOT_PASSWORD: baraka
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
